### ISSUE TITLE
Project migration to VS2013 with QT5.7 and VTK 7.1

### ISSUE THREAD

**Issue by maria364** [WeiqiJust/CHER-Ob#2]
I am trying to migrate CHER-Ob project in Visual Studio 2013 with Qt5.7 and vtk7.1.

I found out that many vtk files have changed through different versions. Is there an easy way to do the migration? The great problem I have so far is with the vtkSource header file which is not included in VTK 7.1.

Thank you in advance.

**Comment by zachzeyuwang** [comment]
We anticipate that it will be a huge amount of work to migrate CHER-Ob using different versions of Qt and VTK. In particular, some VTK functions have their names changed in newer versions. The only approach seems to be to go over all the source files and replace those that are not in compliance with the new standards. If you intend to do so, we would love to give suggestions when you have questions on a specific piece of code. As for the issue of vtkSource header file, please refer to VTK documentation or start with a small program to learn the difference. We also saw your post on stackoverflow. Let us know if you have any further updates.
