### ISSUE TITLE
Compatibility with VS 16.1.3, Windows 10

### ISSUE THREAD

**Issue by irinaciortan** [WeiqiJust/CHER-Ob#3]
Hi,

I just downloaded the source code and tried to compile it. I used all the precompiled libraries, except OpenCV and QT. I have the latest versions of the latter 2. The build fails with the following message: cmd.exe exited with code 3. Do you have any suggestions of how I could make it work?

**Comment by zachzeyuwang** [comment]
We recommend you use the exact versions of all the packages if you'd like to compile from source. That being said, we used Visual Studio 2008 to compile our code with Qt 4.8.5. It's a bit outdated but the latest versions may not be compatible with our source code. You can always install CHER-Ob from the released installer and it should work.
