### ISSUE TITLE
Error when using the executable, Windows 10 platform

### ISSUE THREAD

**Issue by irinaciortan** [WeiqiJust/CHER-Ob#4]
When running the program, with the provided .exe file, if I try to create a project or entity, I always get the error indicating that the XML file couldn't be written. Nonetheless, the file imported (in my case a .ply file) does get opened. So the issue is with saving the project.

**Comment by zachzeyuwang** [comment]
The XML thing seems like what's mentioned in #1. Did you install CHER-Ob from the installer? Did it work well when you opened the executable? Try to run it as administrator. It'll be helpful if you could attach some screenshots of how you installed the program and how you got the error.

**Comment by irinaciortan** [comment]
The 'Run as admin' solved the XML file writing.
