### ISSUE TITLE
Compatibility with new libraries and new IDE

### ISSUE THREAD

**Issue by irinaciortan** [WeiqiJust/CHER-Ob#5]
Regarding the use of newer versions of libraries and Visual Studio, do you think the error comes from the IDE or the libraries? Is there a way to track this down?

**Comment by zachzeyuwang** [comment]
Newer versions of Qt and VTK sometimes use different names for the same function. This means the source code won't compile using newer versions of libraries. You can try compiling the source code with newer versions of libraries and the errors will tell you where goes wrong.
